spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
